#pragma once

#include <cstring>
#include "cctp_trader.h"

class CTrader : public CThostFtdcTraderSpi
{
public:
	CTrader(TraderInfo* trader_info);
	~CTrader();

	int Connect();
	int Disconnect();

private:
	void ReqUserLogin();
	void ReqAuthenticate();
	void InitFlags();

public:
	//api
    const char* GetTradingDay() ;
    void RegisterFront(char* pszFrontAddress) ;
    void RegisterNameServer(char* pszNsAddress) ;
    void RegisterFensUserInfo(CThostFtdcFensUserInfoField * pFensUserInfo) ;
    int RegisterUserSystemInfo(CThostFtdcUserSystemInfoField* pUserSystemInfo) ;
    int SubmitUserSystemInfo(CThostFtdcUserSystemInfoField* pUserSystemInfo) ;
    int ReqUserLogout(CThostFtdcUserLogoutField* pUserLogout, int nRequestID) ;
    int ReqUserPasswordUpdate(CThostFtdcUserPasswordUpdateField* pUserPasswordUpdate, int nRequestID) ;
    int ReqTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField* pTradingAccountPasswordUpdate, int nRequestID) ;
    int ReqUserAuthMethod(CThostFtdcReqUserAuthMethodField* pReqUserAuthMethod, int nRequestID) ;
    int ReqGenUserCaptcha(CThostFtdcReqGenUserCaptchaField* pReqGenUserCaptcha, int nRequestID) ;
    int ReqGenUserText(CThostFtdcReqGenUserTextField* pReqGenUserText, int nRequestID) ;
    int ReqUserLoginWithCaptcha(CThostFtdcReqUserLoginWithCaptchaField* pReqUserLoginWithCaptcha, int nRequestID) ;
    int ReqUserLoginWithText(CThostFtdcReqUserLoginWithTextField* pReqUserLoginWithText, int nRequestID) ;
    int ReqUserLoginWithOTP(CThostFtdcReqUserLoginWithOTPField* pReqUserLoginWithOTP, int nRequestID) ;
    int ReqOrderInsert(CThostFtdcInputOrderField* pInputOrder, int nRequestID) ;
    int ReqParkedOrderInsert(CThostFtdcParkedOrderField* pParkedOrder, int nRequestID) ;
    int ReqParkedOrderAction(CThostFtdcParkedOrderActionField* pParkedOrderAction, int nRequestID) ;
    int ReqOrderAction(CThostFtdcInputOrderActionField* pInputOrderAction, int nRequestID) ;
    int ReqQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField* pQueryMaxOrderVolume, int nRequestID) ;
    int ReqSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField* pSettlementInfoConfirm, int nRequestID) ;
    int ReqRemoveParkedOrder(CThostFtdcRemoveParkedOrderField* pRemoveParkedOrder, int nRequestID) ;
    int ReqRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField* pRemoveParkedOrderAction, int nRequestID) ;
    int ReqExecOrderInsert(CThostFtdcInputExecOrderField* pInputExecOrder, int nRequestID) ;
    int ReqExecOrderAction(CThostFtdcInputExecOrderActionField* pInputExecOrderAction, int nRequestID) ;
    int ReqForQuoteInsert(CThostFtdcInputForQuoteField* pInputForQuote, int nRequestID) ;
    int ReqQuoteInsert(CThostFtdcInputQuoteField* pInputQuote, int nRequestID) ;
    int ReqQuoteAction(CThostFtdcInputQuoteActionField* pInputQuoteAction, int nRequestID) ;
    int ReqBatchOrderAction(CThostFtdcInputBatchOrderActionField* pInputBatchOrderAction, int nRequestID) ;
    int ReqOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField* pInputOptionSelfClose, int nRequestID) ;
    int ReqOptionSelfCloseAction(CThostFtdcInputOptionSelfCloseActionField* pInputOptionSelfCloseAction, int nRequestID) ;
    int ReqCombActionInsert(CThostFtdcInputCombActionField* pInputCombAction, int nRequestID) ;
    int ReqQryOrder(CThostFtdcQryOrderField* pQryOrder, int nRequestID) ;
    int ReqQryTrade(CThostFtdcQryTradeField* pQryTrade, int nRequestID) ;
    int ReqQryInvestorPosition(CThostFtdcQryInvestorPositionField* pQryInvestorPosition, int nRequestID) ;
    int ReqQryTradingAccount(CThostFtdcQryTradingAccountField* pQryTradingAccount, int nRequestID) ;
    int ReqQryInvestor(CThostFtdcQryInvestorField* pQryInvestor, int nRequestID) ;
    int ReqQryTradingCode(CThostFtdcQryTradingCodeField* pQryTradingCode, int nRequestID) ;
    int ReqQryInstrumentMarginRate(CThostFtdcQryInstrumentMarginRateField* pQryInstrumentMarginRate, int nRequestID) ;
    int ReqQryInstrumentCommissionRate(CThostFtdcQryInstrumentCommissionRateField* pQryInstrumentCommissionRate, int nRequestID) ;
    int ReqQryExchange(CThostFtdcQryExchangeField* pQryExchange, int nRequestID) ;
    int ReqQryProduct(CThostFtdcQryProductField* pQryProduct, int nRequestID) ;
    int ReqQryInstrument(CThostFtdcQryInstrumentField* pQryInstrument, int nRequestID) ;
    int ReqQryDepthMarketData(CThostFtdcQryDepthMarketDataField* pQryDepthMarketData, int nRequestID) ;
    int ReqQrySettlementInfo(CThostFtdcQrySettlementInfoField* pQrySettlementInfo, int nRequestID) ;
    int ReqQryTransferBank(CThostFtdcQryTransferBankField* pQryTransferBank, int nRequestID) ;
    int ReqQryInvestorPositionDetail(CThostFtdcQryInvestorPositionDetailField* pQryInvestorPositionDetail, int nRequestID) ;
    int ReqQryNotice(CThostFtdcQryNoticeField* pQryNotice, int nRequestID) ;
    int ReqQrySettlementInfoConfirm(CThostFtdcQrySettlementInfoConfirmField* pQrySettlementInfoConfirm, int nRequestID) ;
    int ReqQryInvestorPositionCombineDetail(CThostFtdcQryInvestorPositionCombineDetailField* pQryInvestorPositionCombineDetail, int nRequestID) ;
    int ReqQryCFMMCTradingAccountKey(CThostFtdcQryCFMMCTradingAccountKeyField* pQryCFMMCTradingAccountKey, int nRequestID) ;
    int ReqQryEWarrantOffset(CThostFtdcQryEWarrantOffsetField* pQryEWarrantOffset, int nRequestID) ;
    int ReqQryInvestorProductGroupMargin(CThostFtdcQryInvestorProductGroupMarginField* pQryInvestorProductGroupMargin, int nRequestID) ;
    int ReqQryExchangeMarginRate(CThostFtdcQryExchangeMarginRateField* pQryExchangeMarginRate, int nRequestID) ;
    int ReqQryExchangeMarginRateAdjust(CThostFtdcQryExchangeMarginRateAdjustField* pQryExchangeMarginRateAdjust, int nRequestID) ;
    int ReqQryExchangeRate(CThostFtdcQryExchangeRateField* pQryExchangeRate, int nRequestID) ;
    int ReqQrySecAgentACIDMap(CThostFtdcQrySecAgentACIDMapField* pQrySecAgentACIDMap, int nRequestID) ;
    int ReqQryProductExchRate(CThostFtdcQryProductExchRateField* pQryProductExchRate, int nRequestID) ;
    int ReqQryProductGroup(CThostFtdcQryProductGroupField* pQryProductGroup, int nRequestID) ;
    int ReqQryMMInstrumentCommissionRate(CThostFtdcQryMMInstrumentCommissionRateField* pQryMMInstrumentCommissionRate, int nRequestID) ;
    int ReqQryMMOptionInstrCommRate(CThostFtdcQryMMOptionInstrCommRateField* pQryMMOptionInstrCommRate, int nRequestID) ;
    int ReqQryInstrumentOrderCommRate(CThostFtdcQryInstrumentOrderCommRateField* pQryInstrumentOrderCommRate, int nRequestID) ;
    int ReqQrySecAgentTradingAccount(CThostFtdcQryTradingAccountField* pQryTradingAccount, int nRequestID) ;
    int ReqQrySecAgentCheckMode(CThostFtdcQrySecAgentCheckModeField* pQrySecAgentCheckMode, int nRequestID) ;
    int ReqQrySecAgentTradeInfo(CThostFtdcQrySecAgentTradeInfoField* pQrySecAgentTradeInfo, int nRequestID) ;
    int ReqQryOptionInstrTradeCost(CThostFtdcQryOptionInstrTradeCostField* pQryOptionInstrTradeCost, int nRequestID) ;
    int ReqQryOptionInstrCommRate(CThostFtdcQryOptionInstrCommRateField* pQryOptionInstrCommRate, int nRequestID) ;
    int ReqQryExecOrder(CThostFtdcQryExecOrderField* pQryExecOrder, int nRequestID) ;
    int ReqQryForQuote(CThostFtdcQryForQuoteField* pQryForQuote, int nRequestID) ;
    int ReqQryQuote(CThostFtdcQryQuoteField* pQryQuote, int nRequestID) ;
    int ReqQryOptionSelfClose(CThostFtdcQryOptionSelfCloseField* pQryOptionSelfClose, int nRequestID) ;
    int ReqQryInvestUnit(CThostFtdcQryInvestUnitField* pQryInvestUnit, int nRequestID) ;
    int ReqQryCombInstrumentGuard(CThostFtdcQryCombInstrumentGuardField* pQryCombInstrumentGuard, int nRequestID) ;
    int ReqQryCombAction(CThostFtdcQryCombActionField* pQryCombAction, int nRequestID) ;
    int ReqQryTransferSerial(CThostFtdcQryTransferSerialField* pQryTransferSerial, int nRequestID) ;
    int ReqQryAccountregister(CThostFtdcQryAccountregisterField* pQryAccountregister, int nRequestID) ;
    int ReqQryContractBank(CThostFtdcQryContractBankField* pQryContractBank, int nRequestID) ;
    int ReqQryParkedOrder(CThostFtdcQryParkedOrderField* pQryParkedOrder, int nRequestID) ;
    int ReqQryParkedOrderAction(CThostFtdcQryParkedOrderActionField* pQryParkedOrderAction, int nRequestID) ;
    int ReqQryTradingNotice(CThostFtdcQryTradingNoticeField* pQryTradingNotice, int nRequestID) ;
    int ReqQryBrokerTradingParams(CThostFtdcQryBrokerTradingParamsField* pQryBrokerTradingParams, int nRequestID) ;
    int ReqQryBrokerTradingAlgos(CThostFtdcQryBrokerTradingAlgosField* pQryBrokerTradingAlgos, int nRequestID) ;
    int ReqQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField* pQueryCFMMCTradingAccountToken, int nRequestID) ;
    int ReqFromBankToFutureByFuture(CThostFtdcReqTransferField* pReqTransfer, int nRequestID) ;
    int ReqFromFutureToBankByFuture(CThostFtdcReqTransferField* pReqTransfer, int nRequestID) ;
    int ReqQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField* pReqQueryAccount, int nRequestID) ;

	//spi
    virtual void OnFrontConnected() ;
    virtual void OnFrontDisconnected(int nReason) ;
    virtual void OnHeartBeatWarning(int nTimeLapse) ;
    virtual void OnRspAuthenticate(CThostFtdcRspAuthenticateField* pRspAuthenticateField, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspUserLogin(CThostFtdcRspUserLoginField* pRspUserLogin, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspUserLogout(CThostFtdcUserLogoutField* pUserLogout, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspUserPasswordUpdate(CThostFtdcUserPasswordUpdateField* pUserPasswordUpdate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField* pTradingAccountPasswordUpdate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspUserAuthMethod(CThostFtdcRspUserAuthMethodField* pRspUserAuthMethod, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspGenUserCaptcha(CThostFtdcRspGenUserCaptchaField* pRspGenUserCaptcha, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspGenUserText(CThostFtdcRspGenUserTextField* pRspGenUserText, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspOrderInsert(CThostFtdcInputOrderField* pInputOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspParkedOrderInsert(CThostFtdcParkedOrderField* pParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspParkedOrderAction(CThostFtdcParkedOrderActionField* pParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspOrderAction(CThostFtdcInputOrderActionField* pInputOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField* pQueryMaxOrderVolume, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField* pSettlementInfoConfirm, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspRemoveParkedOrder(CThostFtdcRemoveParkedOrderField* pRemoveParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField* pRemoveParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspExecOrderInsert(CThostFtdcInputExecOrderField* pInputExecOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspExecOrderAction(CThostFtdcInputExecOrderActionField* pInputExecOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspForQuoteInsert(CThostFtdcInputForQuoteField* pInputForQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQuoteInsert(CThostFtdcInputQuoteField* pInputQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQuoteAction(CThostFtdcInputQuoteActionField* pInputQuoteAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspBatchOrderAction(CThostFtdcInputBatchOrderActionField* pInputBatchOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField* pInputOptionSelfClose, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspOptionSelfCloseAction(CThostFtdcInputOptionSelfCloseActionField* pInputOptionSelfCloseAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspCombActionInsert(CThostFtdcInputCombActionField* pInputCombAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryOrder(CThostFtdcOrderField* pOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryTrade(CThostFtdcTradeField* pTrade, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInvestorPosition(CThostFtdcInvestorPositionField* pInvestorPosition, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryTradingAccount(CThostFtdcTradingAccountField* pTradingAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInvestor(CThostFtdcInvestorField* pInvestor, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryTradingCode(CThostFtdcTradingCodeField* pTradingCode, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInstrumentMarginRate(CThostFtdcInstrumentMarginRateField* pInstrumentMarginRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInstrumentCommissionRate(CThostFtdcInstrumentCommissionRateField* pInstrumentCommissionRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryExchange(CThostFtdcExchangeField* pExchange, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryProduct(CThostFtdcProductField* pProduct, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInstrument(CThostFtdcInstrumentField* pInstrument, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryDepthMarketData(CThostFtdcDepthMarketDataField* pDepthMarketData, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQrySettlementInfo(CThostFtdcSettlementInfoField* pSettlementInfo, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryTransferBank(CThostFtdcTransferBankField* pTransferBank, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInvestorPositionDetail(CThostFtdcInvestorPositionDetailField* pInvestorPositionDetail, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryNotice(CThostFtdcNoticeField* pNotice, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQrySettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField* pSettlementInfoConfirm, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInvestorPositionCombineDetail(CThostFtdcInvestorPositionCombineDetailField* pInvestorPositionCombineDetail, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryCFMMCTradingAccountKey(CThostFtdcCFMMCTradingAccountKeyField* pCFMMCTradingAccountKey, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryEWarrantOffset(CThostFtdcEWarrantOffsetField* pEWarrantOffset, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInvestorProductGroupMargin(CThostFtdcInvestorProductGroupMarginField* pInvestorProductGroupMargin, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryExchangeMarginRate(CThostFtdcExchangeMarginRateField* pExchangeMarginRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryExchangeMarginRateAdjust(CThostFtdcExchangeMarginRateAdjustField* pExchangeMarginRateAdjust, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryExchangeRate(CThostFtdcExchangeRateField* pExchangeRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQrySecAgentACIDMap(CThostFtdcSecAgentACIDMapField* pSecAgentACIDMap, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryProductExchRate(CThostFtdcProductExchRateField* pProductExchRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryProductGroup(CThostFtdcProductGroupField* pProductGroup, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryMMInstrumentCommissionRate(CThostFtdcMMInstrumentCommissionRateField* pMMInstrumentCommissionRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryMMOptionInstrCommRate(CThostFtdcMMOptionInstrCommRateField* pMMOptionInstrCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInstrumentOrderCommRate(CThostFtdcInstrumentOrderCommRateField* pInstrumentOrderCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQrySecAgentTradingAccount(CThostFtdcTradingAccountField* pTradingAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQrySecAgentCheckMode(CThostFtdcSecAgentCheckModeField* pSecAgentCheckMode, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQrySecAgentTradeInfo(CThostFtdcSecAgentTradeInfoField* pSecAgentTradeInfo, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryOptionInstrTradeCost(CThostFtdcOptionInstrTradeCostField* pOptionInstrTradeCost, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryOptionInstrCommRate(CThostFtdcOptionInstrCommRateField* pOptionInstrCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryExecOrder(CThostFtdcExecOrderField* pExecOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryForQuote(CThostFtdcForQuoteField* pForQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryQuote(CThostFtdcQuoteField* pQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryOptionSelfClose(CThostFtdcOptionSelfCloseField* pOptionSelfClose, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryInvestUnit(CThostFtdcInvestUnitField* pInvestUnit, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryCombInstrumentGuard(CThostFtdcCombInstrumentGuardField* pCombInstrumentGuard, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryCombAction(CThostFtdcCombActionField* pCombAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryTransferSerial(CThostFtdcTransferSerialField* pTransferSerial, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryAccountregister(CThostFtdcAccountregisterField* pAccountregister, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspError(CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRtnOrder(CThostFtdcOrderField* pOrder) ;
    virtual void OnRtnTrade(CThostFtdcTradeField* pTrade) ;
    virtual void OnErrRtnOrderInsert(CThostFtdcInputOrderField* pInputOrder, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnOrderAction(CThostFtdcOrderActionField* pOrderAction, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnRtnInstrumentStatus(CThostFtdcInstrumentStatusField* pInstrumentStatus) ;
    virtual void OnRtnBulletin(CThostFtdcBulletinField* pBulletin) ;
    virtual void OnRtnTradingNotice(CThostFtdcTradingNoticeInfoField* pTradingNoticeInfo) ;
    virtual void OnRtnErrorConditionalOrder(CThostFtdcErrorConditionalOrderField* pErrorConditionalOrder) ;
    virtual void OnRtnExecOrder(CThostFtdcExecOrderField* pExecOrder) ;
    virtual void OnErrRtnExecOrderInsert(CThostFtdcInputExecOrderField* pInputExecOrder, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnExecOrderAction(CThostFtdcExecOrderActionField* pExecOrderAction, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnForQuoteInsert(CThostFtdcInputForQuoteField* pInputForQuote, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnRtnQuote(CThostFtdcQuoteField* pQuote) ;
    virtual void OnErrRtnQuoteInsert(CThostFtdcInputQuoteField* pInputQuote, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnQuoteAction(CThostFtdcQuoteActionField* pQuoteAction, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnRtnForQuoteRsp(CThostFtdcForQuoteRspField* pForQuoteRsp) ;
    virtual void OnRtnCFMMCTradingAccountToken(CThostFtdcCFMMCTradingAccountTokenField* pCFMMCTradingAccountToken) ;
    virtual void OnErrRtnBatchOrderAction(CThostFtdcBatchOrderActionField* pBatchOrderAction, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnRtnOptionSelfClose(CThostFtdcOptionSelfCloseField* pOptionSelfClose) ;
    virtual void OnErrRtnOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField* pInputOptionSelfClose, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnOptionSelfCloseAction(CThostFtdcOptionSelfCloseActionField* pOptionSelfCloseAction, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnRtnCombAction(CThostFtdcCombActionField* pCombAction) ;
    virtual void OnErrRtnCombActionInsert(CThostFtdcInputCombActionField* pInputCombAction, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnRspQryContractBank(CThostFtdcContractBankField* pContractBank, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryParkedOrder(CThostFtdcParkedOrderField* pParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryParkedOrderAction(CThostFtdcParkedOrderActionField* pParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryTradingNotice(CThostFtdcTradingNoticeField* pTradingNotice, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryBrokerTradingParams(CThostFtdcBrokerTradingParamsField* pBrokerTradingParams, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQryBrokerTradingAlgos(CThostFtdcBrokerTradingAlgosField* pBrokerTradingAlgos, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField* pQueryCFMMCTradingAccountToken, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRtnFromBankToFutureByBank(CThostFtdcRspTransferField* pRspTransfer) ;
    virtual void OnRtnFromFutureToBankByBank(CThostFtdcRspTransferField* pRspTransfer) ;
    virtual void OnRtnRepealFromBankToFutureByBank(CThostFtdcRspRepealField* pRspRepeal) ;
    virtual void OnRtnRepealFromFutureToBankByBank(CThostFtdcRspRepealField* pRspRepeal) ;
    virtual void OnRtnFromBankToFutureByFuture(CThostFtdcRspTransferField* pRspTransfer) ;
    virtual void OnRtnFromFutureToBankByFuture(CThostFtdcRspTransferField* pRspTransfer) ;
    virtual void OnRtnRepealFromBankToFutureByFutureManual(CThostFtdcRspRepealField* pRspRepeal) ;
    virtual void OnRtnRepealFromFutureToBankByFutureManual(CThostFtdcRspRepealField* pRspRepeal) ;
    virtual void OnRtnQueryBankBalanceByFuture(CThostFtdcNotifyQueryAccountField* pNotifyQueryAccount) ;
    virtual void OnErrRtnBankToFutureByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnFutureToBankByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnRepealBankToFutureByFutureManual(CThostFtdcReqRepealField* pReqRepeal, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnRepealFutureToBankByFutureManual(CThostFtdcReqRepealField* pReqRepeal, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnErrRtnQueryBankBalanceByFuture(CThostFtdcReqQueryAccountField* pReqQueryAccount, CThostFtdcRspInfoField* pRspInfo) ;
    virtual void OnRtnRepealFromBankToFutureByFuture(CThostFtdcRspRepealField* pRspRepeal) ;
    virtual void OnRtnRepealFromFutureToBankByFuture(CThostFtdcRspRepealField* pRspRepeal) ;
    virtual void OnRspFromBankToFutureByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspFromFutureToBankByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRspQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField* pReqQueryAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) ;
    virtual void OnRtnOpenAccountByBank(CThostFtdcOpenAccountField* pOpenAccount) ;
    virtual void OnRtnCancelAccountByBank(CThostFtdcCancelAccountField* pCancelAccount) ;
    virtual void OnRtnChangeAccountByBank(CThostFtdcChangeAccountField* pChangeAccount) ;

    //registered flags
    void registerFP_OnFrontConnected(FuncPtrTradeOnFrontConnected fp);
    void registerFP_OnFrontDisconnected(FuncPtrTradeOnFrontDisconnected fp);
    void registerFP_OnHeartBeatWarning(FuncPtrTradeOnHeartBeatWarning fp);
    void registerFP_OnRspAuthenticate(FuncPtrTradeOnRspAuthenticate fp);
    void registerFP_OnRspUserLogin(FuncPtrTradeOnRspUserLogin fp);
    void registerFP_OnRspUserLogout(FuncPtrTradeOnRspUserLogout fp);
    void registerFP_OnRspUserPasswordUpdate(FuncPtrTradeOnRspUserPasswordUpdate fp);
    void registerFP_OnRspTradingAccountPasswordUpdate(FuncPtrTradeOnRspTradingAccountPasswordUpdate fp);
    void registerFP_OnRspUserAuthMethod(FuncPtrTradeOnRspUserAuthMethod fp);
    void registerFP_OnRspGenUserCaptcha(FuncPtrTradeOnRspGenUserCaptcha fp);
    void registerFP_OnRspGenUserText(FuncPtrTradeOnRspGenUserText fp);
    void registerFP_OnRspOrderInsert(FuncPtrTradeOnRspOrderInsert fp);
    void registerFP_OnRspParkedOrderInsert(FuncPtrTradeOnRspParkedOrderInsert fp);
    void registerFP_OnRspParkedOrderAction(FuncPtrTradeOnRspParkedOrderAction fp);
    void registerFP_OnRspOrderAction(FuncPtrTradeOnRspOrderAction fp);
    void registerFP_OnRspQueryMaxOrderVolume(FuncPtrTradeOnRspQueryMaxOrderVolume fp);
    void registerFP_OnRspSettlementInfoConfirm(FuncPtrTradeOnRspSettlementInfoConfirm fp);
    void registerFP_OnRspRemoveParkedOrder(FuncPtrTradeOnRspRemoveParkedOrder fp);
    void registerFP_OnRspRemoveParkedOrderAction(FuncPtrTradeOnRspRemoveParkedOrderAction fp);
    void registerFP_OnRspExecOrderInsert(FuncPtrTradeOnRspExecOrderInsert fp);
    void registerFP_OnRspExecOrderAction(FuncPtrTradeOnRspExecOrderAction fp);
    void registerFP_OnRspForQuoteInsert(FuncPtrTradeOnRspForQuoteInsert fp);
    void registerFP_OnRspQuoteInsert(FuncPtrTradeOnRspQuoteInsert fp);
    void registerFP_OnRspQuoteAction(FuncPtrTradeOnRspQuoteAction fp);
    void registerFP_OnRspBatchOrderAction(FuncPtrTradeOnRspBatchOrderAction fp);
    void registerFP_OnRspOptionSelfCloseInsert(FuncPtrTradeOnRspOptionSelfCloseInsert fp);
    void registerFP_OnRspOptionSelfCloseAction(FuncPtrTradeOnRspOptionSelfCloseAction fp);
    void registerFP_OnRspCombActionInsert(FuncPtrTradeOnRspCombActionInsert fp);
    void registerFP_OnRspQryOrder(FuncPtrTradeOnRspQryOrder fp);
    void registerFP_OnRspQryTrade(FuncPtrTradeOnRspQryTrade fp);
    void registerFP_OnRspQryInvestorPosition(FuncPtrTradeOnRspQryInvestorPosition fp);
    void registerFP_OnRspQryTradingAccount(FuncPtrTradeOnRspQryTradingAccount fp);
    void registerFP_OnRspQryInvestor(FuncPtrTradeOnRspQryInvestor fp);
    void registerFP_OnRspQryTradingCode(FuncPtrTradeOnRspQryTradingCode fp);
    void registerFP_OnRspQryInstrumentMarginRate(FuncPtrTradeOnRspQryInstrumentMarginRate fp);
    void registerFP_OnRspQryInstrumentCommissionRate(FuncPtrTradeOnRspQryInstrumentCommissionRate fp);
    void registerFP_OnRspQryExchange(FuncPtrTradeOnRspQryExchange fp);
    void registerFP_OnRspQryProduct(FuncPtrTradeOnRspQryProduct fp);
    void registerFP_OnRspQryInstrument(FuncPtrTradeOnRspQryInstrument fp);
    void registerFP_OnRspQryDepthMarketData(FuncPtrTradeOnRspQryDepthMarketData fp);
    void registerFP_OnRspQrySettlementInfo(FuncPtrTradeOnRspQrySettlementInfo fp);
    void registerFP_OnRspQryTransferBank(FuncPtrTradeOnRspQryTransferBank fp);
    void registerFP_OnRspQryInvestorPositionDetail(FuncPtrTradeOnRspQryInvestorPositionDetail fp);
    void registerFP_OnRspQryNotice(FuncPtrTradeOnRspQryNotice fp);
    void registerFP_OnRspQrySettlementInfoConfirm(FuncPtrTradeOnRspQrySettlementInfoConfirm fp);
    void registerFP_OnRspQryInvestorPositionCombineDetail(FuncPtrTradeOnRspQryInvestorPositionCombineDetail fp);
    void registerFP_OnRspQryCFMMCTradingAccountKey(FuncPtrTradeOnRspQryCFMMCTradingAccountKey fp);
    void registerFP_OnRspQryEWarrantOffset(FuncPtrTradeOnRspQryEWarrantOffset fp);
    void registerFP_OnRspQryInvestorProductGroupMargin(FuncPtrTradeOnRspQryInvestorProductGroupMargin fp);
    void registerFP_OnRspQryExchangeMarginRate(FuncPtrTradeOnRspQryExchangeMarginRate fp);
    void registerFP_OnRspQryExchangeMarginRateAdjust(FuncPtrTradeOnRspQryExchangeMarginRateAdjust fp);
    void registerFP_OnRspQryExchangeRate(FuncPtrTradeOnRspQryExchangeRate fp);
    void registerFP_OnRspQrySecAgentACIDMap(FuncPtrTradeOnRspQrySecAgentACIDMap fp);
    void registerFP_OnRspQryProductExchRate(FuncPtrTradeOnRspQryProductExchRate fp);
    void registerFP_OnRspQryProductGroup(FuncPtrTradeOnRspQryProductGroup fp);
    void registerFP_OnRspQryMMInstrumentCommissionRate(FuncPtrTradeOnRspQryMMInstrumentCommissionRate fp);
    void registerFP_OnRspQryMMOptionInstrCommRate(FuncPtrTradeOnRspQryMMOptionInstrCommRate fp);
    void registerFP_OnRspQryInstrumentOrderCommRate(FuncPtrTradeOnRspQryInstrumentOrderCommRate fp);
    void registerFP_OnRspQrySecAgentTradingAccount(FuncPtrTradeOnRspQrySecAgentTradingAccount fp);
    void registerFP_OnRspQrySecAgentCheckMode(FuncPtrTradeOnRspQrySecAgentCheckMode fp);
    void registerFP_OnRspQrySecAgentTradeInfo(FuncPtrTradeOnRspQrySecAgentTradeInfo fp);
    void registerFP_OnRspQryOptionInstrTradeCost(FuncPtrTradeOnRspQryOptionInstrTradeCost fp);
    void registerFP_OnRspQryOptionInstrCommRate(FuncPtrTradeOnRspQryOptionInstrCommRate fp);
    void registerFP_OnRspQryExecOrder(FuncPtrTradeOnRspQryExecOrder fp);
    void registerFP_OnRspQryForQuote(FuncPtrTradeOnRspQryForQuote fp);
    void registerFP_OnRspQryQuote(FuncPtrTradeOnRspQryQuote fp);
    void registerFP_OnRspQryOptionSelfClose(FuncPtrTradeOnRspQryOptionSelfClose fp);
    void registerFP_OnRspQryInvestUnit(FuncPtrTradeOnRspQryInvestUnit fp);
    void registerFP_OnRspQryCombInstrumentGuard(FuncPtrTradeOnRspQryCombInstrumentGuard fp);
    void registerFP_OnRspQryCombAction(FuncPtrTradeOnRspQryCombAction fp);
    void registerFP_OnRspQryTransferSerial(FuncPtrTradeOnRspQryTransferSerial fp);
    void registerFP_OnRspQryAccountregister(FuncPtrTradeOnRspQryAccountregister fp);
    void registerFP_OnRspError(FuncPtrTradeOnRspError fp);
    void registerFP_OnRtnOrder(FuncPtrTradeOnRtnOrder fp);
    void registerFP_OnRtnTrade(FuncPtrTradeOnRtnTrade fp);
    void registerFP_OnErrRtnOrderInsert(FuncPtrTradeOnErrRtnOrderInsert fp);
    void registerFP_OnErrRtnOrderAction(FuncPtrTradeOnErrRtnOrderAction fp);
    void registerFP_OnRtnInstrumentStatus(FuncPtrTradeOnRtnInstrumentStatus fp);
    void registerFP_OnRtnBulletin(FuncPtrTradeOnRtnBulletin fp);
    void registerFP_OnRtnTradingNotice(FuncPtrTradeOnRtnTradingNotice fp);
    void registerFP_OnRtnErrorConditionalOrder(FuncPtrTradeOnRtnErrorConditionalOrder fp);
    void registerFP_OnRtnExecOrder(FuncPtrTradeOnRtnExecOrder fp);
    void registerFP_OnErrRtnExecOrderInsert(FuncPtrTradeOnErrRtnExecOrderInsert fp);
    void registerFP_OnErrRtnExecOrderAction(FuncPtrTradeOnErrRtnExecOrderAction fp);
    void registerFP_OnErrRtnForQuoteInsert(FuncPtrTradeOnErrRtnForQuoteInsert fp);
    void registerFP_OnRtnQuote(FuncPtrTradeOnRtnQuote fp);
    void registerFP_OnErrRtnQuoteInsert(FuncPtrTradeOnErrRtnQuoteInsert fp);
    void registerFP_OnErrRtnQuoteAction(FuncPtrTradeOnErrRtnQuoteAction fp);
    void registerFP_OnRtnForQuoteRsp(FuncPtrTradeOnRtnForQuoteRsp fp);
    void registerFP_OnRtnCFMMCTradingAccountToken(FuncPtrTradeOnRtnCFMMCTradingAccountToken fp);
    void registerFP_OnErrRtnBatchOrderAction(FuncPtrTradeOnErrRtnBatchOrderAction fp);
    void registerFP_OnRtnOptionSelfClose(FuncPtrTradeOnRtnOptionSelfClose fp);
    void registerFP_OnErrRtnOptionSelfCloseInsert(FuncPtrTradeOnErrRtnOptionSelfCloseInsert fp);
    void registerFP_OnErrRtnOptionSelfCloseAction(FuncPtrTradeOnErrRtnOptionSelfCloseAction fp);
    void registerFP_OnRtnCombAction(FuncPtrTradeOnRtnCombAction fp);
    void registerFP_OnErrRtnCombActionInsert(FuncPtrTradeOnErrRtnCombActionInsert fp);
    void registerFP_OnRspQryContractBank(FuncPtrTradeOnRspQryContractBank fp);
    void registerFP_OnRspQryParkedOrder(FuncPtrTradeOnRspQryParkedOrder fp);
    void registerFP_OnRspQryParkedOrderAction(FuncPtrTradeOnRspQryParkedOrderAction fp);
    void registerFP_OnRspQryTradingNotice(FuncPtrTradeOnRspQryTradingNotice fp);
    void registerFP_OnRspQryBrokerTradingParams(FuncPtrTradeOnRspQryBrokerTradingParams fp);
    void registerFP_OnRspQryBrokerTradingAlgos(FuncPtrTradeOnRspQryBrokerTradingAlgos fp);
    void registerFP_OnRspQueryCFMMCTradingAccountToken(FuncPtrTradeOnRspQueryCFMMCTradingAccountToken fp);
    void registerFP_OnRtnFromBankToFutureByBank(FuncPtrTradeOnRtnFromBankToFutureByBank fp);
    void registerFP_OnRtnFromFutureToBankByBank(FuncPtrTradeOnRtnFromFutureToBankByBank fp);
    void registerFP_OnRtnRepealFromBankToFutureByBank(FuncPtrTradeOnRtnRepealFromBankToFutureByBank fp);
    void registerFP_OnRtnRepealFromFutureToBankByBank(FuncPtrTradeOnRtnRepealFromFutureToBankByBank fp);
    void registerFP_OnRtnFromBankToFutureByFuture(FuncPtrTradeOnRtnFromBankToFutureByFuture fp);
    void registerFP_OnRtnFromFutureToBankByFuture(FuncPtrTradeOnRtnFromFutureToBankByFuture fp);
    void registerFP_OnRtnRepealFromBankToFutureByFutureManual(FuncPtrTradeOnRtnRepealFromBankToFutureByFutureManual fp);
    void registerFP_OnRtnRepealFromFutureToBankByFutureManual(FuncPtrTradeOnRtnRepealFromFutureToBankByFutureManual fp);
    void registerFP_OnRtnQueryBankBalanceByFuture(FuncPtrTradeOnRtnQueryBankBalanceByFuture fp);
    void registerFP_OnErrRtnBankToFutureByFuture(FuncPtrTradeOnErrRtnBankToFutureByFuture fp);
    void registerFP_OnErrRtnFutureToBankByFuture(FuncPtrTradeOnErrRtnFutureToBankByFuture fp);
    void registerFP_OnErrRtnRepealBankToFutureByFutureManual(FuncPtrTradeOnErrRtnRepealBankToFutureByFutureManual fp);
    void registerFP_OnErrRtnRepealFutureToBankByFutureManual(FuncPtrTradeOnErrRtnRepealFutureToBankByFutureManual fp);
    void registerFP_OnErrRtnQueryBankBalanceByFuture(FuncPtrTradeOnErrRtnQueryBankBalanceByFuture fp);
    void registerFP_OnRtnRepealFromBankToFutureByFuture(FuncPtrTradeOnRtnRepealFromBankToFutureByFuture fp);
    void registerFP_OnRtnRepealFromFutureToBankByFuture(FuncPtrTradeOnRtnRepealFromFutureToBankByFuture fp);
    void registerFP_OnRspFromBankToFutureByFuture(FuncPtrTradeOnRspFromBankToFutureByFuture fp);
    void registerFP_OnRspFromFutureToBankByFuture(FuncPtrTradeOnRspFromFutureToBankByFuture fp);
    void registerFP_OnRspQueryBankAccountMoneyByFuture(FuncPtrTradeOnRspQueryBankAccountMoneyByFuture fp);
    void registerFP_OnRtnOpenAccountByBank(FuncPtrTradeOnRtnOpenAccountByBank fp);
    void registerFP_OnRtnCancelAccountByBank(FuncPtrTradeOnRtnCancelAccountByBank fp);
    void registerFP_OnRtnChangeAccountByBank(FuncPtrTradeOnRtnChangeAccountByBank fp);

private:
	CThostFtdcTraderApi *m_pApi;
	TraderInfo m_trader_info;

	//registered flags
    bool m_onFrontConnectedRegistered;
    bool m_onFrontDisconnectedRegistered;
    bool m_onHeartBeatWarningRegistered;
    bool m_onRspAuthenticateRegistered;
    bool m_onRspUserLoginRegistered;
    bool m_onRspUserLogoutRegistered;
    bool m_onRspUserPasswordUpdateRegistered;
    bool m_onRspTradingAccountPasswordUpdateRegistered;
    bool m_onRspUserAuthMethodRegistered;
    bool m_onRspGenUserCaptchaRegistered;
    bool m_onRspGenUserTextRegistered;
    bool m_onRspOrderInsertRegistered;
    bool m_onRspParkedOrderInsertRegistered;
    bool m_onRspParkedOrderActionRegistered;
    bool m_onRspOrderActionRegistered;
    bool m_onRspQueryMaxOrderVolumeRegistered;
    bool m_onRspSettlementInfoConfirmRegistered;
    bool m_onRspRemoveParkedOrderRegistered;
    bool m_onRspRemoveParkedOrderActionRegistered;
    bool m_onRspExecOrderInsertRegistered;
    bool m_onRspExecOrderActionRegistered;
    bool m_onRspForQuoteInsertRegistered;
    bool m_onRspQuoteInsertRegistered;
    bool m_onRspQuoteActionRegistered;
    bool m_onRspBatchOrderActionRegistered;
    bool m_onRspOptionSelfCloseInsertRegistered;
    bool m_onRspOptionSelfCloseActionRegistered;
    bool m_onRspCombActionInsertRegistered;
    bool m_onRspQryOrderRegistered;
    bool m_onRspQryTradeRegistered;
    bool m_onRspQryInvestorPositionRegistered;
    bool m_onRspQryTradingAccountRegistered;
    bool m_onRspQryInvestorRegistered;
    bool m_onRspQryTradingCodeRegistered;
    bool m_onRspQryInstrumentMarginRateRegistered;
    bool m_onRspQryInstrumentCommissionRateRegistered;
    bool m_onRspQryExchangeRegistered;
    bool m_onRspQryProductRegistered;
    bool m_onRspQryInstrumentRegistered;
    bool m_onRspQryDepthMarketDataRegistered;
    bool m_onRspQrySettlementInfoRegistered;
    bool m_onRspQryTransferBankRegistered;
    bool m_onRspQryInvestorPositionDetailRegistered;
    bool m_onRspQryNoticeRegistered;
    bool m_onRspQrySettlementInfoConfirmRegistered;
    bool m_onRspQryInvestorPositionCombineDetailRegistered;
    bool m_onRspQryCFMMCTradingAccountKeyRegistered;
    bool m_onRspQryEWarrantOffsetRegistered;
    bool m_onRspQryInvestorProductGroupMarginRegistered;
    bool m_onRspQryExchangeMarginRateRegistered;
    bool m_onRspQryExchangeMarginRateAdjustRegistered;
    bool m_onRspQryExchangeRateRegistered;
    bool m_onRspQrySecAgentACIDMapRegistered;
    bool m_onRspQryProductExchRateRegistered;
    bool m_onRspQryProductGroupRegistered;
    bool m_onRspQryMMInstrumentCommissionRateRegistered;
    bool m_onRspQryMMOptionInstrCommRateRegistered;
    bool m_onRspQryInstrumentOrderCommRateRegistered;
    bool m_onRspQrySecAgentTradingAccountRegistered;
    bool m_onRspQrySecAgentCheckModeRegistered;
    bool m_onRspQrySecAgentTradeInfoRegistered;
    bool m_onRspQryOptionInstrTradeCostRegistered;
    bool m_onRspQryOptionInstrCommRateRegistered;
    bool m_onRspQryExecOrderRegistered;
    bool m_onRspQryForQuoteRegistered;
    bool m_onRspQryQuoteRegistered;
    bool m_onRspQryOptionSelfCloseRegistered;
    bool m_onRspQryInvestUnitRegistered;
    bool m_onRspQryCombInstrumentGuardRegistered;
    bool m_onRspQryCombActionRegistered;
    bool m_onRspQryTransferSerialRegistered;
    bool m_onRspQryAccountregisterRegistered;
    bool m_onRspErrorRegistered;
    bool m_onRtnOrderRegistered;
    bool m_onRtnTradeRegistered;
    bool m_onErrRtnOrderInsertRegistered;
    bool m_onErrRtnOrderActionRegistered;
    bool m_onRtnInstrumentStatusRegistered;
    bool m_onRtnBulletinRegistered;
    bool m_onRtnTradingNoticeRegistered;
    bool m_onRtnErrorConditionalOrderRegistered;
    bool m_onRtnExecOrderRegistered;
    bool m_onErrRtnExecOrderInsertRegistered;
    bool m_onErrRtnExecOrderActionRegistered;
    bool m_onErrRtnForQuoteInsertRegistered;
    bool m_onRtnQuoteRegistered;
    bool m_onErrRtnQuoteInsertRegistered;
    bool m_onErrRtnQuoteActionRegistered;
    bool m_onRtnForQuoteRspRegistered;
    bool m_onRtnCFMMCTradingAccountTokenRegistered;
    bool m_onErrRtnBatchOrderActionRegistered;
    bool m_onRtnOptionSelfCloseRegistered;
    bool m_onErrRtnOptionSelfCloseInsertRegistered;
    bool m_onErrRtnOptionSelfCloseActionRegistered;
    bool m_onRtnCombActionRegistered;
    bool m_onErrRtnCombActionInsertRegistered;
    bool m_onRspQryContractBankRegistered;
    bool m_onRspQryParkedOrderRegistered;
    bool m_onRspQryParkedOrderActionRegistered;
    bool m_onRspQryTradingNoticeRegistered;
    bool m_onRspQryBrokerTradingParamsRegistered;
    bool m_onRspQryBrokerTradingAlgosRegistered;
    bool m_onRspQueryCFMMCTradingAccountTokenRegistered;
    bool m_onRtnFromBankToFutureByBankRegistered;
    bool m_onRtnFromFutureToBankByBankRegistered;
    bool m_onRtnRepealFromBankToFutureByBankRegistered;
    bool m_onRtnRepealFromFutureToBankByBankRegistered;
    bool m_onRtnFromBankToFutureByFutureRegistered;
    bool m_onRtnFromFutureToBankByFutureRegistered;
    bool m_onRtnRepealFromBankToFutureByFutureManualRegistered;
    bool m_onRtnRepealFromFutureToBankByFutureManualRegistered;
    bool m_onRtnQueryBankBalanceByFutureRegistered;
    bool m_onErrRtnBankToFutureByFutureRegistered;
    bool m_onErrRtnFutureToBankByFutureRegistered;
    bool m_onErrRtnRepealBankToFutureByFutureManualRegistered;
    bool m_onErrRtnRepealFutureToBankByFutureManualRegistered;
    bool m_onErrRtnQueryBankBalanceByFutureRegistered;
    bool m_onRtnRepealFromBankToFutureByFutureRegistered;
    bool m_onRtnRepealFromFutureToBankByFutureRegistered;
    bool m_onRspFromBankToFutureByFutureRegistered;
    bool m_onRspFromFutureToBankByFutureRegistered;
    bool m_onRspQueryBankAccountMoneyByFutureRegistered;
    bool m_onRtnOpenAccountByBankRegistered;
    bool m_onRtnCancelAccountByBankRegistered;
    bool m_onRtnChangeAccountByBankRegistered;

	//function pointers
    FuncPtrTradeOnFrontConnected m_fpOnFrontConnected;
    FuncPtrTradeOnFrontDisconnected m_fpOnFrontDisconnected;
    FuncPtrTradeOnHeartBeatWarning m_fpOnHeartBeatWarning;
    FuncPtrTradeOnRspAuthenticate m_fpOnRspAuthenticate;
    FuncPtrTradeOnRspUserLogin m_fpOnRspUserLogin;
    FuncPtrTradeOnRspUserLogout m_fpOnRspUserLogout;
    FuncPtrTradeOnRspUserPasswordUpdate m_fpOnRspUserPasswordUpdate;
    FuncPtrTradeOnRspTradingAccountPasswordUpdate m_fpOnRspTradingAccountPasswordUpdate;
    FuncPtrTradeOnRspUserAuthMethod m_fpOnRspUserAuthMethod;
    FuncPtrTradeOnRspGenUserCaptcha m_fpOnRspGenUserCaptcha;
    FuncPtrTradeOnRspGenUserText m_fpOnRspGenUserText;
    FuncPtrTradeOnRspOrderInsert m_fpOnRspOrderInsert;
    FuncPtrTradeOnRspParkedOrderInsert m_fpOnRspParkedOrderInsert;
    FuncPtrTradeOnRspParkedOrderAction m_fpOnRspParkedOrderAction;
    FuncPtrTradeOnRspOrderAction m_fpOnRspOrderAction;
    FuncPtrTradeOnRspQueryMaxOrderVolume m_fpOnRspQueryMaxOrderVolume;
    FuncPtrTradeOnRspSettlementInfoConfirm m_fpOnRspSettlementInfoConfirm;
    FuncPtrTradeOnRspRemoveParkedOrder m_fpOnRspRemoveParkedOrder;
    FuncPtrTradeOnRspRemoveParkedOrderAction m_fpOnRspRemoveParkedOrderAction;
    FuncPtrTradeOnRspExecOrderInsert m_fpOnRspExecOrderInsert;
    FuncPtrTradeOnRspExecOrderAction m_fpOnRspExecOrderAction;
    FuncPtrTradeOnRspForQuoteInsert m_fpOnRspForQuoteInsert;
    FuncPtrTradeOnRspQuoteInsert m_fpOnRspQuoteInsert;
    FuncPtrTradeOnRspQuoteAction m_fpOnRspQuoteAction;
    FuncPtrTradeOnRspBatchOrderAction m_fpOnRspBatchOrderAction;
    FuncPtrTradeOnRspOptionSelfCloseInsert m_fpOnRspOptionSelfCloseInsert;
    FuncPtrTradeOnRspOptionSelfCloseAction m_fpOnRspOptionSelfCloseAction;
    FuncPtrTradeOnRspCombActionInsert m_fpOnRspCombActionInsert;
    FuncPtrTradeOnRspQryOrder m_fpOnRspQryOrder;
    FuncPtrTradeOnRspQryTrade m_fpOnRspQryTrade;
    FuncPtrTradeOnRspQryInvestorPosition m_fpOnRspQryInvestorPosition;
    FuncPtrTradeOnRspQryTradingAccount m_fpOnRspQryTradingAccount;
    FuncPtrTradeOnRspQryInvestor m_fpOnRspQryInvestor;
    FuncPtrTradeOnRspQryTradingCode m_fpOnRspQryTradingCode;
    FuncPtrTradeOnRspQryInstrumentMarginRate m_fpOnRspQryInstrumentMarginRate;
    FuncPtrTradeOnRspQryInstrumentCommissionRate m_fpOnRspQryInstrumentCommissionRate;
    FuncPtrTradeOnRspQryExchange m_fpOnRspQryExchange;
    FuncPtrTradeOnRspQryProduct m_fpOnRspQryProduct;
    FuncPtrTradeOnRspQryInstrument m_fpOnRspQryInstrument;
    FuncPtrTradeOnRspQryDepthMarketData m_fpOnRspQryDepthMarketData;
    FuncPtrTradeOnRspQrySettlementInfo m_fpOnRspQrySettlementInfo;
    FuncPtrTradeOnRspQryTransferBank m_fpOnRspQryTransferBank;
    FuncPtrTradeOnRspQryInvestorPositionDetail m_fpOnRspQryInvestorPositionDetail;
    FuncPtrTradeOnRspQryNotice m_fpOnRspQryNotice;
    FuncPtrTradeOnRspQrySettlementInfoConfirm m_fpOnRspQrySettlementInfoConfirm;
    FuncPtrTradeOnRspQryInvestorPositionCombineDetail m_fpOnRspQryInvestorPositionCombineDetail;
    FuncPtrTradeOnRspQryCFMMCTradingAccountKey m_fpOnRspQryCFMMCTradingAccountKey;
    FuncPtrTradeOnRspQryEWarrantOffset m_fpOnRspQryEWarrantOffset;
    FuncPtrTradeOnRspQryInvestorProductGroupMargin m_fpOnRspQryInvestorProductGroupMargin;
    FuncPtrTradeOnRspQryExchangeMarginRate m_fpOnRspQryExchangeMarginRate;
    FuncPtrTradeOnRspQryExchangeMarginRateAdjust m_fpOnRspQryExchangeMarginRateAdjust;
    FuncPtrTradeOnRspQryExchangeRate m_fpOnRspQryExchangeRate;
    FuncPtrTradeOnRspQrySecAgentACIDMap m_fpOnRspQrySecAgentACIDMap;
    FuncPtrTradeOnRspQryProductExchRate m_fpOnRspQryProductExchRate;
    FuncPtrTradeOnRspQryProductGroup m_fpOnRspQryProductGroup;
    FuncPtrTradeOnRspQryMMInstrumentCommissionRate m_fpOnRspQryMMInstrumentCommissionRate;
    FuncPtrTradeOnRspQryMMOptionInstrCommRate m_fpOnRspQryMMOptionInstrCommRate;
    FuncPtrTradeOnRspQryInstrumentOrderCommRate m_fpOnRspQryInstrumentOrderCommRate;
    FuncPtrTradeOnRspQrySecAgentTradingAccount m_fpOnRspQrySecAgentTradingAccount;
    FuncPtrTradeOnRspQrySecAgentCheckMode m_fpOnRspQrySecAgentCheckMode;
    FuncPtrTradeOnRspQrySecAgentTradeInfo m_fpOnRspQrySecAgentTradeInfo;
    FuncPtrTradeOnRspQryOptionInstrTradeCost m_fpOnRspQryOptionInstrTradeCost;
    FuncPtrTradeOnRspQryOptionInstrCommRate m_fpOnRspQryOptionInstrCommRate;
    FuncPtrTradeOnRspQryExecOrder m_fpOnRspQryExecOrder;
    FuncPtrTradeOnRspQryForQuote m_fpOnRspQryForQuote;
    FuncPtrTradeOnRspQryQuote m_fpOnRspQryQuote;
    FuncPtrTradeOnRspQryOptionSelfClose m_fpOnRspQryOptionSelfClose;
    FuncPtrTradeOnRspQryInvestUnit m_fpOnRspQryInvestUnit;
    FuncPtrTradeOnRspQryCombInstrumentGuard m_fpOnRspQryCombInstrumentGuard;
    FuncPtrTradeOnRspQryCombAction m_fpOnRspQryCombAction;
    FuncPtrTradeOnRspQryTransferSerial m_fpOnRspQryTransferSerial;
    FuncPtrTradeOnRspQryAccountregister m_fpOnRspQryAccountregister;
    FuncPtrTradeOnRspError m_fpOnRspError;
    FuncPtrTradeOnRtnOrder m_fpOnRtnOrder;
    FuncPtrTradeOnRtnTrade m_fpOnRtnTrade;
    FuncPtrTradeOnErrRtnOrderInsert m_fpOnErrRtnOrderInsert;
    FuncPtrTradeOnErrRtnOrderAction m_fpOnErrRtnOrderAction;
    FuncPtrTradeOnRtnInstrumentStatus m_fpOnRtnInstrumentStatus;
    FuncPtrTradeOnRtnBulletin m_fpOnRtnBulletin;
    FuncPtrTradeOnRtnTradingNotice m_fpOnRtnTradingNotice;
    FuncPtrTradeOnRtnErrorConditionalOrder m_fpOnRtnErrorConditionalOrder;
    FuncPtrTradeOnRtnExecOrder m_fpOnRtnExecOrder;
    FuncPtrTradeOnErrRtnExecOrderInsert m_fpOnErrRtnExecOrderInsert;
    FuncPtrTradeOnErrRtnExecOrderAction m_fpOnErrRtnExecOrderAction;
    FuncPtrTradeOnErrRtnForQuoteInsert m_fpOnErrRtnForQuoteInsert;
    FuncPtrTradeOnRtnQuote m_fpOnRtnQuote;
    FuncPtrTradeOnErrRtnQuoteInsert m_fpOnErrRtnQuoteInsert;
    FuncPtrTradeOnErrRtnQuoteAction m_fpOnErrRtnQuoteAction;
    FuncPtrTradeOnRtnForQuoteRsp m_fpOnRtnForQuoteRsp;
    FuncPtrTradeOnRtnCFMMCTradingAccountToken m_fpOnRtnCFMMCTradingAccountToken;
    FuncPtrTradeOnErrRtnBatchOrderAction m_fpOnErrRtnBatchOrderAction;
    FuncPtrTradeOnRtnOptionSelfClose m_fpOnRtnOptionSelfClose;
    FuncPtrTradeOnErrRtnOptionSelfCloseInsert m_fpOnErrRtnOptionSelfCloseInsert;
    FuncPtrTradeOnErrRtnOptionSelfCloseAction m_fpOnErrRtnOptionSelfCloseAction;
    FuncPtrTradeOnRtnCombAction m_fpOnRtnCombAction;
    FuncPtrTradeOnErrRtnCombActionInsert m_fpOnErrRtnCombActionInsert;
    FuncPtrTradeOnRspQryContractBank m_fpOnRspQryContractBank;
    FuncPtrTradeOnRspQryParkedOrder m_fpOnRspQryParkedOrder;
    FuncPtrTradeOnRspQryParkedOrderAction m_fpOnRspQryParkedOrderAction;
    FuncPtrTradeOnRspQryTradingNotice m_fpOnRspQryTradingNotice;
    FuncPtrTradeOnRspQryBrokerTradingParams m_fpOnRspQryBrokerTradingParams;
    FuncPtrTradeOnRspQryBrokerTradingAlgos m_fpOnRspQryBrokerTradingAlgos;
    FuncPtrTradeOnRspQueryCFMMCTradingAccountToken m_fpOnRspQueryCFMMCTradingAccountToken;
    FuncPtrTradeOnRtnFromBankToFutureByBank m_fpOnRtnFromBankToFutureByBank;
    FuncPtrTradeOnRtnFromFutureToBankByBank m_fpOnRtnFromFutureToBankByBank;
    FuncPtrTradeOnRtnRepealFromBankToFutureByBank m_fpOnRtnRepealFromBankToFutureByBank;
    FuncPtrTradeOnRtnRepealFromFutureToBankByBank m_fpOnRtnRepealFromFutureToBankByBank;
    FuncPtrTradeOnRtnFromBankToFutureByFuture m_fpOnRtnFromBankToFutureByFuture;
    FuncPtrTradeOnRtnFromFutureToBankByFuture m_fpOnRtnFromFutureToBankByFuture;
    FuncPtrTradeOnRtnRepealFromBankToFutureByFutureManual m_fpOnRtnRepealFromBankToFutureByFutureManual;
    FuncPtrTradeOnRtnRepealFromFutureToBankByFutureManual m_fpOnRtnRepealFromFutureToBankByFutureManual;
    FuncPtrTradeOnRtnQueryBankBalanceByFuture m_fpOnRtnQueryBankBalanceByFuture;
    FuncPtrTradeOnErrRtnBankToFutureByFuture m_fpOnErrRtnBankToFutureByFuture;
    FuncPtrTradeOnErrRtnFutureToBankByFuture m_fpOnErrRtnFutureToBankByFuture;
    FuncPtrTradeOnErrRtnRepealBankToFutureByFutureManual m_fpOnErrRtnRepealBankToFutureByFutureManual;
    FuncPtrTradeOnErrRtnRepealFutureToBankByFutureManual m_fpOnErrRtnRepealFutureToBankByFutureManual;
    FuncPtrTradeOnErrRtnQueryBankBalanceByFuture m_fpOnErrRtnQueryBankBalanceByFuture;
    FuncPtrTradeOnRtnRepealFromBankToFutureByFuture m_fpOnRtnRepealFromBankToFutureByFuture;
    FuncPtrTradeOnRtnRepealFromFutureToBankByFuture m_fpOnRtnRepealFromFutureToBankByFuture;
    FuncPtrTradeOnRspFromBankToFutureByFuture m_fpOnRspFromBankToFutureByFuture;
    FuncPtrTradeOnRspFromFutureToBankByFuture m_fpOnRspFromFutureToBankByFuture;
    FuncPtrTradeOnRspQueryBankAccountMoneyByFuture m_fpOnRspQueryBankAccountMoneyByFuture;
    FuncPtrTradeOnRtnOpenAccountByBank m_fpOnRtnOpenAccountByBank;
    FuncPtrTradeOnRtnCancelAccountByBank m_fpOnRtnCancelAccountByBank;
    FuncPtrTradeOnRtnChangeAccountByBank m_fpOnRtnChangeAccountByBank;

};